### PR TITLE
Add Windows build

### PR DESCRIPTION
**Pull request by mcbarton**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

This PR should add a Windows build to the package.

### CODE REVIEW

**Comment by mcbarton** [comment]
@conda-forge-admin, please rerender

**Comment by mcbarton** [comment]
@conda-forge-admin, please rerender

**Comment by mcbarton** [comment]
@vgvassilev @alexander-penev @JohanMabille @SylvainCorlay can one of you review this PR for me please?

**Comment by vgvassilev** [comment]
LGTM. @alexander-penev what do you think? Shall we suppress the warning in that PR the way we did for CppInterOp or we can do it in a subsequent PR?

**Review by alexander-penev — APPROVED** [review]

**Pull request merged**
